### ISSUE TITLE
request: instructions on how to install the app from CI or CLI

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hub-dashboard-predtimechart#13]
I realized that while I am able to run the app locally with

```
python src/hub_predtimechart/app/generate_json_files.py [... args ...]
```

I am not sure how to install this app on CLI or via GitHub Actions. I tried `pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart/`, but I got an error:

<details>
<summary>error output of pip</summary>

```
$ pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart
Collecting git+https://github.com/hubverse-org/hub-dashboard-predtimechart
  Cloning https://github.com/hubverse-org/hub-dashboard-predtimechart to /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-req-build-k4_2b111
  Running command git clone --filter=blob:none --quiet https://github.com/hubverse-org/hub-dashboard-predtimechart /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-req-build-k4_2b111
  Resolved https://github.com/hubverse-org/hub-dashboard-predtimechart to commit c7afbdae3f7f94309f056faaf362f62775abf6b8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas (from hub-dashboard-predtimechart==0.0.1)
  Downloading pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (89 kB)
Requirement already satisfied: pyyaml in /Users/zkamvar/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from hub-dashboard-predtimechart==0.0.1) (6.0)
Collecting structlog (from hub-dashboard-predtimechart==0.0.1)
  Using cached structlog-24.4.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pyarrow (from hub-dashboard-predtimechart==0.0.1)
  Downloading pyarrow-17.0.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (3.3 kB)
Collecting jsonschema (from hub-dashboard-predtimechart==0.0.1)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting attrs>=22.2.0 (from jsonschema->hub-dashboard-predtimechart==0.0.1)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->hub-dashboard-predtimechart==0.0.1)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema->hub-dashboard-predtimechart==0.0.1)
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema->hub-dashboard-predtimechart==0.0.1)
  Downloading rpds_py-0.20.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (4.2 kB)
Collecting numpy>=1.22.4 (from pandas->hub-dashboard-predtimechart==0.0.1)
  Downloading numpy-2.1.1-cp310-cp310-macosx_14_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zkamvar/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from pandas->hub-dashboard-predtimechart==0.0.1) (2.8.2)
Collecting pytz>=2020.1 (from pandas->hub-dashboard-predtimechart==0.0.1)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->hub-dashboard-predtimechart==0.0.1)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/zkamvar/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->hub-dashboard-predtimechart==0.0.1) (1.16.0)
Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
Downloading pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 4.5 MB/s eta 0:00:00
Downloading pyarrow-17.0.0-cp310-cp310-macosx_11_0_arm64.whl (27.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 9.5 MB/s eta 0:00:00
Using cached structlog-24.4.0-py3-none-any.whl (67 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Downloading numpy-2.1.1-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 11.3 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached referencing-0.35.1-py3-none-any.whl (26 kB)
Downloading rpds_py-0.20.0-cp310-cp310-macosx_11_0_arm64.whl (311 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Building wheels for collected packages: hub-dashboard-predtimechart
  Building wheel for hub-dashboard-predtimechart (pyproject.toml) ... done
  Created wheel for hub-dashboard-predtimechart: filename=hub_dashboard_predtimechart-0.0.1-py3-none-any.whl size=15204 sha256=799db72267303e71cdbd508862089e8421fdad610ffb2bda821fa442f0ceae7f
  Stored in directory: /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-ephem-wheel-cache-fjbeaf5_/wheels/9a/2d/0b/d9708f602b90584a04580e4ad250ff64ed40db26298c20f173
Successfully built hub-dashboard-predtimechart
Installing collected packages: pytz, tzdata, structlog, rpds-py, numpy, attrs, referencing, pyarrow, pandas, jsonschema-specifications, jsonschema, hub-dashboard-predtimechart
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.8.3 requires numpy<2,>=1.21, but you have numpy 2.1.1 which is incompatible.
Successfully installed attrs-24.2.0 hub-dashboard-predtimechart-0.0.1 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 numpy-2.1.1 pandas-2.2.3 pyarrow-17.0.0 pytz-2024.2 referencing-0.35.1 rpds-py-0.20.0 structlog-24.4.0 tzdata-2024.2
```

</details>

Beyond that.... I'm not sure exactly how I would actually use it and I would appreciate some help with that.

**Comment by zkamvar** [comment]
One of the problems was that I was not installing this in a virtual environment and my existing matplotlib says "no"

I have been able to install this locally with

```bash
$ pip install -r requirements/requirements.txt && pip install -e .
```

However, when I try to run the app, I get this:

```bash
$ hub_predtimechart --help
Traceback (most recent call last):
  File "/path/to/hubverse-org/hub-dashboard-predtimechart/.venv/bin/hub_predtimechart", line 5, in <module>
    from hub_predtimechart.app import main
ImportError: cannot import name 'main' from 'hub_predtimechart.app' (/path/to/hubverse-org/hub-dashboard-predtimechart/src/hub_predtimechart/app/__init__.py)
```

**Comment by zkamvar** [comment]
I was able to get this to work by changing this line to add `generate_json_file`

https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/c7afbdae3f7f94309f056faaf362f62775abf6b8/pyproject.toml#L27-L28

```diff
 [project.entry-points."console_scripts"]
-hub_predtimechart = "hub_predtimechart.app:main"
+hub_predtimechart = "hub_predtimechart.app.generate_json_files:main"
```

And from there, I was able to get the CLI to work:

```bash
$ hub_predtimechart --help
Usage: hub_predtimechart [OPTIONS] HUB_DIR PTC_CONFIG_FILE OPTIONS_FILE_OUT
                         FORECASTS_OUT_DIR

  An app that generates the options json file and forecast json files required
  by https://github.com/reichlab/predtimechart to visualize a hub's forecasts.

  :param hub_dir: (input) a directory Path of a https://hubverse.io hub to
  generate forecast json files from :param ptc_config_file: (input) a file
  Path to a `predtimechart-config.yaml` file that specifies how to process
  `hub_dir` to get predtimechart output :param options_file_out: (output) a
  file Path to output the predtimechart options object file to (see
  https://github.com/reichlab/predtimechart?tab=readme-ov-file#options-object
  ) :param forecasts_out_dir: (output) a directory Path to output the viz
  forecast json files to

Options:
  --help  Show this message and exit.
```


For a non-local install, I have attempted to run a regular `pip install` command, but it does not work because the dependencies are not brought along with the app. 

```bash
tmp=$(mktemp -d)
python -m venv .venv
source .venv/bin/activate
pip install /path/to/hub-dashboard-predtimechart
# installation notification messages
hub_predtimechart --help
Traceback (most recent call last):
  File "/private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.kaa57a2pMt/.venv/bin/hub_predtimechart", line 5, in <module>
    from hub_predtimechart.app.generate_json_files import main
  File "/private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.kaa57a2pMt/.venv/lib/python3.12/site-packages/hub_predtimechart/app/generate_json_files.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by matthewcornell** [comment]
Thanks very much for the detective work, @zkamvar ! I'm sorry you're having trouble. This is my first time developing a "proper" python package, and I started with @bsweger 's https://github.com/reichlab/reichlab-python-template , so I'm going to ask her to chime in.

Regarding the `[project.entry-points."console_scripts"]` entry, good catch. I'll commit your fix in a bit.

**Comment by zkamvar** [comment]
> This is my first time developing a "proper" python package

TIL! 

My other question is: Will the interface to generate the predtimechart JSON file be available?

Are you expecting this to be a CLI utility or a module?

**Comment by matthewcornell** [comment]
> Will the interface to generate the predtimechart JSON file be available?
Not sure what you're asking.

> Are you expecting this to be a CLI utility or a module?
I think CLI - the expected use is from a script, if that's what you're after, and not another python program.

**Comment by zkamvar** [comment]
> Not sure what you're asking.

My mistake. I forgot that this generated the predtimechart options JSON file.

**Comment by bsweger** [comment]
To the question of how to install this package and run the CLI app, I think we're on the right track with fixing up the `entry-point` in `pyproject.toml` as suggested above.

Once the entry point correctly points to whatever function represents the `click` app, a user should be able to:

1. pip install `hub_predtimechart` from github (like @zkamvar's incantation above: `pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart/`)
2. type `hub_predtimechart` to fire up the CLI

The error report in the body of the issue is a good old-fashioned python dependency conflict and resolved when Zhian tried the install in a new virtual environment.

If we want to explore shielding users from worrying about python and virtual env installs, we could explore some of [uv's](https://docs.astral.sh/uv/) new features.

There are also tools that create executable files from Python code, though I've never explored them.

❓ Who or what will execute this CLI? Is it something that will happen via CI, or will a hub admin be running it? I think the answer to how we package this up depends on the answer.

**Comment by zkamvar** [comment]
Here's what happens when I install in a fresh python environment, I get the error `ModuleNotFoundError: No module named 'click'`, which somehow means that the dependencies of the app are not being resolved.

```
07:50:35 ~
$ tmp=$(mktemp -d)
07:50:43 ~
$ cd $tmp
07:50:45 /var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC
$ python -m venv .venv
07:50:55 /var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC
$ source .venv/bin/activate
07:51:01 /var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC
$ pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart/
```

<details>
<summary>Installation output junk</summary>

```
Collecting git+https://github.com/hubverse-org/hub-dashboard-predtimechart/
  Cloning https://github.com/hubverse-org/hub-dashboard-predtimechart/ to /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-req-build-txjoevuw
  Running command git clone --filter=blob:none --quiet https://github.com/hubverse-org/hub-dashboard-predtimechart/ /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-req-build-txjoevuw
  Resolved https://github.com/hubverse-org/hub-dashboard-predtimechart/ to commit d62e68f955ceefe3a2f0b3cf19cd46319b55a461
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting structlog
  Downloading structlog-24.4.0-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.2/67.2 kB 1.3 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 19.3 MB/s eta 0:00:00
Collecting jsonschema
  Downloading jsonschema-4.23.0-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 7.1 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0.2-cp310-cp310-macosx_11_0_arm64.whl (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.8/171.8 kB 17.2 MB/s eta 0:00:00
Collecting pyarrow
  Downloading pyarrow-17.0.0-cp310-cp310-macosx_11_0_arm64.whl (27.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 23.1 MB/s eta 0:00:00
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.20.0-cp310-cp310-macosx_11_0_arm64.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.3/311.3 kB 19.0 MB/s eta 0:00:00
Collecting attrs>=22.2.0
  Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 7.7 MB/s eta 0:00:00
Collecting referencing>=0.28.4
  Downloading referencing-0.35.1-py3-none-any.whl (26 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 17.3 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 31.4 MB/s eta 0:00:00
Collecting numpy>=1.22.4
  Downloading numpy-2.1.1-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 28.2 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 25.0 MB/s eta 0:00:00
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: hub-dashboard-predtimechart
  Building wheel for hub-dashboard-predtimechart (pyproject.toml) ... done
  Created wheel for hub-dashboard-predtimechart: filename=hub_dashboard_predtimechart-0.0.1-py3-none-any.whl size=15304 sha256=d09d5f2c4f6e60a5bdb250bd8926da9ab5f05513463dd7d039475cf4594f3efc
  Stored in directory: /private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/pip-ephem-wheel-cache-nocx2wfy/wheels/32/18/b9/6f0d5d1cd57127bb8a0a4d664694058904e1e462cd2a0ae588
Successfully built hub-dashboard-predtimechart
Installing collected packages: pytz, tzdata, structlog, six, rpds-py, pyyaml, numpy, attrs, referencing, python-dateutil, pyarrow, pandas, jsonschema-specifications, jsonschema, hub-dashboard-predtimechart
Successfully installed attrs-24.2.0 hub-dashboard-predtimechart-0.0.1 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 numpy-2.1.1 pandas-2.2.3 pyarrow-17.0.0 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 referencing-0.35.1 rpds-py-0.20.0 six-1.16.0 structlog-24.4.0 tzdata-2024.2

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
```

</details>

```
07:51:28 /var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC
$ hub_predtimechart --help
Traceback (most recent call last):
  File "/private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC/.venv/bin/hub_predtimechart", line 5, in <module>
    from hub_predtimechart.app.generate_json_files import main
  File "/private/var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC/.venv/lib/python3.10/site-packages/hub_predtimechart/app/generate_json_files.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
07:51:38 /var/folders/9p/m996p3_55hjf1hc62552cqfr0000gr/T/tmp.E1mfs4j0zC
$ 
```

**Comment by zkamvar** [comment]
>  Who or what will execute this CLI? Is it something that will happen via CI, or will a hub admin be running it? I think the answer to how we package this up depends on the answer.

The idea would be to run this on CI with something like:

```yaml
    steps:
      - id: generate-json
        run: |
          pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart/
          hub_predtimechart <ARGUMENTS>
```

**Comment by bsweger** [comment]
Ah, it looks like `click` is missing from the dependencies list in `pyproject.toml`: https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/main/pyproject.toml#L13

The process for adding new dependencies to the package is:

1. Add the dependency to pyproject.toml, which allows the package to be installed with all required dependencies
2. From pyproject.toml, dev uses preferred tool (pipenv, uv, pip-compile, etc.) to generate the updated `requirements.txt` file needed for devs to reproduce a consistent environment


The existing "code check" GitHub workflow follows the "dev setup" approach w/ `requirements.txt` to ensure a consistent environment for running tests, etc.
